server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    instance:
    hostname: true
spring:
  application:
    name: DEPARTMENT-SERVICE